server:
  port: 8080
spring:
  application:
    name: form-login-demo
#  security:
#    user:
#      password: 123456
#      name: user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/spring_security?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
  thymeleaf:
    cache: false
    mode: html
    prefix: classpath:/templates/
    suffix: .html
    enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    properties:
      "hibernate.format_sql": true
    database: mysql
logging:
  level:
    root: info