server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        #hostname: 127.0.0.1
        service-name: ${spring.application.name}
    gateway:
#      routes:
#        #将 payment-8007 8006 提供的服务隐藏起来，不暴露给客户端，只给客户端暴露 API 网关的地址 9527
#        - id: provider_payment_consul_routh   #路由 id,没有固定规则，但唯一，建议与服务名对应
#          uri: lb://consul-provider-payment
#          predicates:
#            - Path=/payment/consul/**    #断言，路径匹配 注意：Path 中 P 为大写
#            - Method=GET #只能时 GET 请求时，才能访问
##            - Token=myToken123456
#          filters:
#            - AddRequestHeader=name1,xixi
#            - AddRequestHeader=name2, haha
#            - AddRequestParameter=username,password
      enabled: true
      redis-route-definition-repository:
        enabled: true
      discovery:
        locator:
          enabled: true # 让gateway从consul中获取服务信息
          lower-case-service-id: true
  redis:
    host: 192.168.0.155 # 添加 redis 用作存放动态路由
management:
  endpoints:
    web:
      exposure:
        include: "*"