server:
  port: 9527

spring:
  application:
    name: api-gateway
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
    gateway:
      routes:
        - id: provider_payment_consul_routh
          uri: lb://consul-provider-payment
          predicates:
            - Path=/provider/**
          filters:
            - RewritePath=/provider/(?<segment>.*), /$\{segment} #路径重写的过滤器，在yml中$写为 $\
      #            - name: WhiteList
      #              args:
      #                value: zhazha,xixi
      #            - SetResponseHeader=X-Response-Red,Blue
      #            - MapRequestHeader=Blue, X-Request-Red
      enabled: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true